/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projekti;

import javax.swing.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Flamur
 */
public class FshijeUserinFrame extends javax.swing.JFrame {

    // Variables declaration - do not modify
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;

    /**
     * Creates new form FshijeUserinFrame
     */
    public FshijeUserinFrame() throws IOException {
        initComponents();
        setTitle("Fshije receten");
        setSize(410, 360);
        setLocationRelativeTo(null);
        setVisible(true);
        UserMapper um = new UserMapper();
        for (int i = 0; i < um.getUsers().size(); i++) {
            choice1.add(um.getUsers().get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        choice1 = new java.awt.Choice();
        jButton1 = new javax.swing.JButton();

        jButton1.setText("Fshije");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(FshijeUserinFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UserException ex) {
                    Logger.getLogger(FshijeUserinFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1)
                                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(252, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException, UserException {
        UserMapper um = new UserMapper();
        um.fshijeUserin(choice1.getSelectedItem());
        JOptionPane.showMessageDialog(null, "Keni fshier Userin : " + choice1.getSelectedItem() + " me sukses!");
        choice1.remove(choice1.getSelectedItem());
        this.setVisible(false);
    }
    // End of variables declaration                   
}
